### ISSUE TITLE
current time calculations dont work for non UTC timezone

### ISSUE THREAD

**Issue by alansaviolobo** [n0nag0n/simple-job-queue#3]
```
$added_dt = gmdate('Y-m-d H:i:s');
$time_to_retry_dt = gmdate('Y-m-d H:i:s', strtotime('now +'.$time_to_retry.' seconds UTC'));
```
These two lines of code dont give consistent results when your timezone is something other than UTC.
This causes the worker to not pick up any jobs.

Sample Code run:
```
date_default_timezone_set("Asia/Kolkata");
var_dump(gmdate('Y-m-d H:i:s'));
var_dump(gmdate('Y-m-d H:i:s', strtotime('now +5 seconds UTC')));
```
retults in 
> string(19) "2024-05-05 17:09:50"
> string(19) "2024-05-05 22:39:55"

**Comment by alansaviolobo** [comment]
removing the  **UTC** seems to do the trick.
To be removed in 4 places.

**Comment by n0nag0n** [comment]
Good catch! Why I put gmdate() and UTC in the same line....is beyond me. Should be fixed now. I'll go ahead and add a release.

https://github.com/n0nag0n/simple-job-queue/commit/60293574f289e8008e36469657e54145d6529150
