### ISSUE TITLE
support for Postgre SQL ?

### ISSUE THREAD

**Issue by alansaviolobo** [n0nag0n/simple-job-queue#4]
any thoughts on supporting postgres ?

**Comment by n0nag0n** [comment]
I think it'd be a great idea, but I have no desire to implement it cause I would never use it on any of my projects (they are all MySQL/MariaDB and SQLite). If you work with it, I'm sure that it would be a very easy addition to the code to make it work.

**Comment by alansaviolobo** [comment]
ill give it a shot.

Regards,
Alan Lobo

**Comment by alansaviolobo** [comment]
The first issue i encountered is that pgsql doesnt appear to support datetime data types.
![pgsql](https://github.com/n0nag0n/simple-job-queue/assets/1202289/28aea58d-1dc3-4f91-8f1c-4f8e4c13a34e)

This affects **added_dt**, **send_dt**, **reserved_dt**, **buried_dt** columns. In these added_dt and buried_dt dont appear to be used (just stored).

any thoughts on converting these columns to timestamp / integer ?

**Comment by n0nag0n** [comment]
Hmm, so it might get icky to convert sqlite and mysql to time stamps with those users that are currently using it. What you could do is have a char/varchar column equivalent in postgres and limit it to 19 characters and then index it. That would work wouldn't it? It wouldn't officially be a datetime equivalent but should get the job done.

**Comment by alansaviolobo** [comment]
i suppose i could use the sqlite db  creation syntax as is.
will have to remove the single quotes

Regards,
Alan Lobo

**Comment by alansaviolobo** [comment]
the postgres table creation and job queuing is done. Please review in the fork whenever feasible.

**Comment by n0nag0n** [comment]
I checked it out and ran tests, besides some spacing issues, it looks great! Wanna create a PR? Thanks so much!

**Comment by alansaviolobo** [comment]
Ill create the pr after i run the worker

I noticed the spacing too. My IDE is configured for different spacing.

**Comment by n0nag0n** [comment]
Just checking in on this. Appreciation your help with it!

**Comment by alansaviolobo** [comment]
havent forgotten.
just that I am in touch with quite a few vendors to get their API and when
I get the API I will end up testing this along with that code.

Regards,
Alan Lobo

**Comment by alansaviolobo** [comment]
https://github.com/n0nag0n/simple-job-queue/pull/5

**Comment by n0nag0n** [comment]
Thanks so much!
