### ISSUE TITLE
handling db disconnection issues

### ISSUE THREAD

**Issue by alansaviolobo** [n0nag0n/simple-job-queue#6]
I came across a situation where the db connection would break and that exception/error would cause the worker to crash.
to over come that, I have a situation involving a loop inside a loop. its a bit wierd so wanted a second opinion on the same.

the example worker script would also have to be updated accordingly

```while (true) {
      try {
        $starttime = microtime(true);
        $PDO = new PDO($dsn);
        $Job_Queue = new Job_Queue('pgsql', ['pgsql' => ['table_name' => 'tankertasks']]);
        $Job_Queue->addQueueConnection($PDO);
        $Job_Queue->watchPipeline('tracker');
        while (true) {
          $job = $Job_Queue->getNextJobAndReserve();

          if (empty($job)) {
            echo '.';
            usleep(500 * 1000);
            continue;
          }

          try {
            $payload = json_decode($job['payload'], true);
            if (class_exists($payload['gpsProvider'])) {
              new $payload['gpsProvider']($payload['tanker'], $payload['cacheKey']);
              $Job_Queue->deleteJob($job);
            }
          } catch (Exception $e) {
            $Job_Queue->buryJob($job);
          }
        }
      } catch (Exception $e) {
       // error handlng here
      }
    }```

**Comment by alansaviolobo** [comment]
another issue is that all my jobs appear to get burried and not deleted.

**Comment by n0nag0n** [comment]
In your code, my guess is that the exception is thrown and the traceroute bubbles up to this line? Can you confirm?

```php
$job = $Job_Queue->getNextJobAndReserve();
```

**Comment by n0nag0n** [comment]
Ping

**Comment by alansaviolobo** [comment]
> Ping

apologies. yes. the catch was causing the jobs to be buried which was creating a huge backlog.
have replaced the line with a $Job_Queue->deleteJob($job); since the job is redundant if not run immediately.

**Comment by n0nag0n** [comment]
Cool cool, glad it's fixed!
